[pytest]
DJANGO_SETTINGS_MODULE = backend.srvs.office.office.settings
python_files = test_*.py
addopts = --reuse-db --nomigrations --cov=backend/srvs/office --cov-report=term-missing --strict-markers
