# Generated by Django 5.2.7 on 2025-11-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.IntegerField(choices=[(1, 'Question'), (2, 'Content')])),
                ('order', models.PositiveIntegerField()),
                ('show_leaderboard_after', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='anonymous', max_length=100)),
                ('music_url', models.URLField(blank=True, max_length=500, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='office.slide')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], max_length=10)),
                ('min_point', models.IntegerField(default=0)),
                ('max_point', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(default=30)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('faster_answers_more_points', models.BooleanField(default=False)),
                ('partial_scoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='office.quiz'),
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rust_session_id', models.CharField(max_length=255, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='office.question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('quiz', 'order')},
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rust_session_id', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.question')),
            ],
            options={
                'unique_together': {('question', 'rust_session_id')},
            },
        ),
    ]
