# Generated by Django 5.2.7 on 2025-11-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_question_text_alter_question_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
    ]
