# Generated by Django 5.2.7 on 2025-11-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_quiz_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='music',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='content_image',
        ),
        migrations.AddField(
            model_name='option',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='background_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='music_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='content_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
