# Generated by Django 5.2.7 on 2025-11-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_option_options_option_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickanswerquestion',
            name='max_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pickanswerquestion',
            name='min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickanswerquestion',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_retries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='current_question_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='default_time_per_question',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points_calculation',
            field=models.CharField(choices=[('accuracy_based', 'بر اساس دقت'), ('time_based', 'بر اساس زمان'), ('fixed', 'ثابت')], default='accuracy_based', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('is_host', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='office.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('submit_time', models.FloatField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.pickanswerquestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.option')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='office.participant')),
            ],
            options={
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
