# Generated by Django 5.2.7 on 2025-11-10 15:20

import backend.srvs.office.office.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_option_explanation_pickanswerquestion_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='default_time_per_question',
            field=models.IntegerField(default=30, validators=[backend.srvs.office.office.validators.validate_positive_time, backend.srvs.office.office.validators.validate_reasonable_time]),
        ),
    ]
