# Generated by Django 5.2.8 on 2026-01-31 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_alter_quiz_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='access_code must be 4-16 chars and use letters, numbers, "_" or "-" only', regex='^[A-Za-z0-9_-]{4,16}$')]),
        ),
    ]
