# Generated by Django 5.2.8 on 2026-02-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_alter_quiz_access_code'),
        ('office', '0017_add_quiz_text_color'),
    ]

    operations = [
    ]
